github.com:
    users:
        salmansamer827-cmyk:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: salmansamer827-cmyk
