[GDrive]
type = drive
scope = drive
token = {"access_token":"ya29.a0Aa7MYiqZSLss90n1mWZ0uJZqgJoiW9PB7XGN-x6o8yVjG20mNHolpriyLfQwYIbTyNBh3CINNl8chv4XZ2ZzBLhkB5B2PE6xY01N3YxlI9VLduPr4j-g_YY29rE2Ui5yZLIlPf4B-Y3uHXQBAELXy2t11Ofdl8fYWSyQvSdcAdNnZ-x2nSSpVDFm3PMFj3JRvl1yABQ-aCgYKAZQSARQSFQHGX2MirapiGEMgDnmWc3ulBDGWmA0207","token_type":"Bearer","refresh_token":"1//03dKznl4QU1yTCgYIARAAGAMSNwF-L9Iro2zmyQUbL9jG6IF_bLxNogY-UhUbYUy1Ht_UicfeyaogZOaNy9Jvn44DjBmBoS0aSLQ","expiry":"2026-04-04T19:03:23.993527883Z","expires_in":3599}
team_drive = 

[gdrive]
type = drive
scope = drive
team_drive = 

