name: Build APK
on: [push]
jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build Debug APK
        run: |
          if [ -d "android" ]; then
            cd android && chmod +x gradlew && ./gradlew assembleDebug
          else
            echo "Android directory not found!" && exit 1
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: EXCORA-PRO-V1
          path: android/app/build/outputs/apk/debug/*.apk

